// The public face of a weekly report: /r/<token>.
//
// This is the only route in the application that renders a client's data
// without a session, so the constraints on it are listed here rather than left
// to be inferred:
//
//  - GET only. There is nothing to submit, and no state-changing method means
//     the CSRF verifier this router is mounted under has nothing to check.
//  - No session is created and none is read. A member of the team opening a
//     share link sees exactly what the client sees, which is also the only
//     honest way to check what was sent.
//  - `noindex, noarchive` plus `Referrer-Policy: no-referrer`. A capability URL
//     that Googlebot finds in a client's forwarded email is a capability URL in
//     the index; the referrer header would leak the token to any site linked
//     from the page.
//  - `Cache-Control: private, no-store`. A shared proxy caching this response
//     would serve one client's report on another client's request for the same
//     URL - unlikely, and catastrophic, which is the combination that gets a
//     header rather than a comment.
//  - It renders aggregates only. See lib/leads.js: no lead's name, email or
//     phone number reaches this template.
const express = require('express');
const shares = require('../lib/reportShares');
const leads = require('../lib/leads');

const router = express.Router();

// A failed link gets a real page with a real explanation, not the app's 404.
// The person reading it is a client who was sent a link by their agency, and
// "No page at /r/xyz" tells them nothing and makes the agency look broken.
function refuse(res, reason, share) {
  const messages = {
    [shares.EXPIRED]: share && share.expires_on
      ? `This report link expired on ${share.expires_on}.`
      : 'This report link has expired.',
    [shares.REVOKED]: 'This report link has been turned off.',
    [shares.INVALID]: 'This report link is not valid. It may have been mistyped, or the report may have been removed.',
  };
  res.status(reason === shares.INVALID ? 404 : 410)
    .set('Cache-Control', 'private, no-store')
    .render('share-unavailable', {
      layout: false,
      heading: reason === shares.EXPIRED ? 'This link has expired' : 'This link is not available',
      message: messages[reason] || messages[shares.INVALID],
    });
}

router.get('/:token', (req, res, next) => {
  try {
    const result = shares.resolve(req.params.token);
    if (!result.ok) return refuse(res, result.reason, result.share);

    shares.recordView(result.share.id);

    const report = result.report;
    // Lead numbers are attached for the report's own week, not for whatever
    // window the app happens to default to - a client reading a report dated
    // three weeks ago should see that week's enquiries, not this week's.
    let leadSummary = null;
    try {
      if (leads.hasAny(report.brand_id)) {
        leadSummary = leads.summary(report.brand_id, {
          from: report.period_start,
          to: report.period_end,
        });
      }
    } catch (e) {
      // A failure here must not take down the report. The leads section is an
      // addition to a document that was complete without it.
      console.error('[share] lead summary failed:', e.message);
    }

    res.set({
      'X-Robots-Tag': 'noindex, nofollow, noarchive',
      'Referrer-Policy': 'no-referrer',
      'Cache-Control': 'private, no-store',
    });
    return res.render('report-print', {
      layout: false,
      row: report,
      d: report.data,
      // The flag the shared template branches on. Everything it hides is
      // internal: the app's own links, the raw JSON/Excel exports, and the
      // "generated by" line that names a machine rather than a person.
      share: { label: result.share.label, views: result.share.views },
      brand: {
        company: report.report_company,
        logoUrl: report.report_logo_url,
        accent: report.report_accent,
        footer: report.report_footer,
        contact: report.report_contact,
      },
      commentary: report.commentary || null,
      leadSummary,
    });
  } catch (err) { return next(err); }
});

module.exports = router;
